

#------------------------------------------------------------------------------#
#
# CRCRDM: Robust Decision Making tools for Colorectal Cancer Screening Models
#
# Author: Pedro Nascimento de Lima
# See LICENSE.txt and README.txt for information on usage and licensing
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
# CRC Model Class
# Purpose: The crcmodel class represents or contains the
# more crcmodels.
# Creation Date: July 2021
#------------------------------------------------------------------------------#

#' R6 Class Representing a `crcmodel`
#'
#' @description
#' This class implements a `crcmodel`.
#'
#' @import R6
#' @export
crcmodel <- R6::R6Class(
  classname = "crcmodel",
  # Use public to expose methods of this class:
  public = list(

    #' @field name is a character string representing the model name (e.g. CRC-SPIN v 2.1)
    name = NULL,
    #' @field inputs is a list of model inputs. One can add inputs to the object with the set_input function.
    inputs = NULL,
    #' @field inputs_table is a data.frame listing all inputs added to the model.
    inputs_table = NULL,
    #' @field posterior_params is a data.frame containing parameters from the posterior distribution of the model. This table is set with the set_posterior function.
    posterior_params = NULL,

    #' @field simulate_screening_fn is is the function used to simulate screening.
    simulate_screening_fn = NULL,

    #' @field natural_history_results is the object that will receive results from the natural history function.
    natural_history_results = NULL,

    #' @field screening_results is the object that will receive results from the natural history function.
    screening_results = NULL,

    #' @description
    #' Create a new `crcmodel` object.
    #' @param name name of the model to be created.
    #' @return s new `crcmodel` object.
    initialize = function(name) {
      stopifnot(is.character(name), length(name) == 1)
      self$name <- name
      # Initializing inputs objects:
      self$inputs = list()
      self$inputs_table = data.frame(name = character(), type = character())
    },

    #' @description
    #' Set Input
    #'
    #' @details
    #' Use this function to add a new input to a crcmodel object.
    #' All model inputs shoulhd be added or modified through this function. Inputs can be vectors or lists of strings, numeric or integers, to guarantee that they can be translated to and from JSON without any issues.
    #'
    #' @param name character string defining the input name
    #' @param value input value. Can be a single value, a list or a vector.
    #' @param type Functionality TBD, but inputs can be filtered by type.
    set_input = function(name, value, type){
      crcmodel_set_input(self = self, name = name, value = value, type = type)
    },

    #' @description
    #' Converts a `crcmodel` to a JSON string
    #' @return a JSON string containing the crcmodel objects that should be exported
    to_json = function() {
      crcmodel_to_json(self = self, private = private)
    },

    #' @description
    #' Set model Inputs from JSON string
    #'
    #' @details
    #' Use this function to set model inputs from a JSON string. Note that the posterior distribution is not included in the json strong of model inputs.
    #'
    #' @param json a JSON string generated by the model_to_json function
    set_inputs_from_json = function(json){
      crcmodel_set_inputs_from_json(self = self, json = json)
    },

    #' @description
    #' Set Posterior distribution of model parameters
    #'
    #' @details
    #' Use this function to add a new input to a crcmodel object.
    #' All model inputs shoulhd be added or modified through this function. Inputs can be vectors or lists of strings, numeric or integers, to guarantee that they can be translated to and from JSON without any issues.
    #'
    #' @param posteriors_list named list of one more more data.frames containing the posterior of model parameters.
    #' @param posterior_weights character indicating the name of the column that contain weights to be used when sampling from the posterior
    #' @param n_posterior the size of the sample to take from each posterior file.
    #' @param use_average T if one wants to use the average value of all parameters rather than the mean
    #' @param seed random seed to use when sampling from the posterior
    set_posterior = function(posteriors_list, posterior_weights, n_posterior, use_average = F, seed = 12345678){
      crcmodel_set_posterior(self = self, posteriors_list = posteriors_list, posterior_weights = posterior_weights, use_average = use_average, n_posterior = n_posterior, seed = seed)
    },

    #' @description
    #' Set Natural History Function
    #'
    #' @details
    #' This function allows the user to have a custom natural history function. Having this flexibility effectively decouples the model itself from the package that is used to simulate the model. As in a regression, the functional form of the model is not baked into `lm`. Instead, `lm` allows you to create *any* linear model.
    #' Use this function to define a natural history function. You are advised to create a simple natural history function and put a `browser()` inside it. Then, after creating your model with `my_model <- crcmodel$new()` and adding inputs with `my_model$set_input()`, assign your custom natural history function with `my_model$set_natural_history(my_function_name)`. `my_function_name` should the name of a function that you already sourced from a script or from a package. Finally, run `my_model$simulate_natural_history()` to run your natural history model. You will then see all your inputs inside the `self` object, which is an environment that contains all the inputs for your model.
    #' @param natural_history_fn an R function that is capable of simulating the model's natural history.
    #' @param returns_standardized_df if TRUE, your natural history function must return a standardized dataframe.
    set_natural_history_fn = function(natural_history_fn, returns_standardized_df = T){
      self$simulate_natural_history_fn <- natural_history_fn
    },

    #' @description
    #' Set Screening Function
    #'
    #' @details
    #' This function allows the user to have a custom screening function.
    #' @seealso set_natural_history_fn
    #' @param screening_fn an R function that is capable of simulating the model's screening.
    #' @param returns_standardized_df if TRUE, your natural history function must return a standardized dataframe.
    set_screening_fn = function(screening_fn, returns_standardized_df = T){
      self$simulate_screening_fn <- screening_fn
    },

    #' @description
    #' Simulate Natural History Wrapper Function
    #'
    #' @details
    #' This function is a wrapper around the user natural history function. It passes the `self` object and any other parameters provided to the function.
    #' @seealso set_natural_history_fn
    #' @param ... any set of parameters passed to this function will be passed along to the user natural history function.
    simulate_natural_history = function(...){
      self$natural_history_results = self$simulate_natural_history_fn(self = self, ...)
      invisible(self)
    },

    #' @description
    #' Simulate Screening Wrapper Function
    #'
    #' @details
    #' This function is a wrapper around the user screening. It passes the `self` object and any other parameters provided to the function.
    #' @seealso set_screening_fn
    #' @param ... any set of parameters passed to this function will be passed along to the user screening function.
    simulate_screening = function(...){
      self$screening_results = self$simulate_screening_fn(self = self, ...)
      invisible(self)
    }

  ),
  # Use private to hold data that will not be accessed by the user directly.
  private = list(
    # Private objects are not documented and exported as R6 fields:
    #character vector with names of data.frame objects. This is used when converting objects to and from json.
    df_objects = c("inputs_table"),
    #character vector of list of objects to convert to and from
    json_objects = c("inputs", "inputs_table")
  ),
  # Use active binding functions to get and set the private data
  active = list()
  # Initialize function is used to initialize the object:
)


#' Checks if object is a `crcmodel`.
#'
#' @param x the model object
#'
#' @return TRUE if object is a crcmodel
#' @export
is.crcmodel = function(x){
  "crcmodel" %in% class(x)
}
